### PR TITLE
innersourcecommons.org/learningpath redirect

### PR DESCRIPTION
**Pull request by rrrutledge**
* Copied https://github.com/paypal/InnerSourceCommons/blob/master/pages/gdrive.md
* Not sure how to test.

### CODE REVIEW

**Comment by lenucksi** [comment]
I would suggest the following approach:
- If we currently do not have such a redirect and thus can not interrupt the main site traffic: deploy, test, revert if needed. Rinse & repeat 
- If we do already have such a redirect and might interrupt the main site traffic, deploy to the isc.net environment, test there.

**Comment by rrrutledge** [comment]
We currently do not have such a redirect so I'd go with door #1.

**Comment by NewMexicoKid** [comment]
The way I do it is to do a test build on my own website server, but I understand not everyone has this resource available. Also, I thought the learning path repo had been moved to its final destination? Is it necessary to do an intermediate redirect to bit.ly?

**Comment by rrrutledge** [comment]
> Is it necessary to do an intermediate redirect to bit.ly?

Good point - we can point to the page on the inner source commons website that explains about the learning path.  Eventually the videos should be hosted there as well.

**Pull request merged**
