### PR TITLE
Update Jekyll to Version 3.8

### PR DESCRIPTION
**Pull request by maxcapraro**
Problem: 
Jekyll 3.0.2 and Ruby 2.5.1 appear to be not compatible. On Windows I had some trouble installing RVM to downgrade to an older Ruby version.

Proposed solution:
This PR upgrades the build setup to work with Ruby 2.5.1 and Jekyll 3.8. 

- Update ruby version used in travis
- Update jeckyl version in Gemfile
- Recreate Gemfile.lock

I did not observe any side effects but don't know the build setup well. **Please merge with care!**

### CODE REVIEW

**Comment by maxcapraro** [comment]
I'll look into the breaking build tomorrow. Sorry about that.

**Comment by maxcapraro** [comment]
Fixed broken build by dropping platform specifics from `Gemfile.lock`

**Comment by maxcapraro** [comment]
Not sure about the travis config but I see a red **x**. Should we revert and discard this MR,  @NewMexicoKid ?

**Comment by NewMexicoKid** [comment]
Okay, Max. I tried; the code itself looked benign, but who knows...

**Pull request merged**
