### PR TITLE
Migrating article list from inner-sourcing.com

### PR DESCRIPTION
**Pull request by nyeates**
Attempting to fix link format from @kjstol and added a quick explanation sentence at
the top

### CODE REVIEW

**Comment by nyeates** [comment]
Adding more links from 2004

**Comment by nyeates** [comment]
Yet more links! 2005 complete

**Comment by cewilliams** [comment]
Site content default license updated to CC-BY-SA 4.0. Please confirm you are submitting under that license? Thanks!

**Comment by nyeates** [comment]
Confirmed that license is known to be CC-BY-SA 4.0. Pull away!

**Comment by cewilliams** [comment]
Thanks!

**Pull request merged**
