### PR TITLE
Remove ISC Fall event (already happened)

### PR DESCRIPTION
**Pull request by rrrutledge**
I haven't tested it out yet, but seems safe enough?

Plus want to try out the web site editing during the session

### CODE REVIEW

**Comment by cewilliams** [comment]
I'd prefer to revert back to the previous text than wipe out the layout. Please update the text instead when you re-submit.

**Comment by cewilliams** [comment]
As discussed in person: Sidebar changes seem to break the template fairly easily so I want to avoid dealing with that chaos.

**Comment by rrrutledge** [comment]
It looks like the previous test was the Spring summit (with dates).  We really don't want to revert back to that.  Do we know the dates of the next summit?

https://github.com/paypal/InnerSourceCommons/commit/3e93d4e4c5110c9031e5e1210c9b2314dd412ec6#diff-e67a3ecb4eaf560b683cdd7f82de4e1c

**Comment by cewilliams** [comment]
We don't know the dates or location yet. I've used the generic "Join us at the next summit" linking to the events page when the next one wasn't known. Something like 36448826b498d44635cf6f1f9ede1249ffeb0ac6

**Comment by rrrutledge** [comment]
OK have another look

**Comment by cewilliams** [comment]
Almost perfect! Please update the H3 link to point to the events page as well - maybe use "ISC Events" instead of "ICS Summit" ?

**Comment by rrrutledge** [comment]
Thanks for finding that.  Sorry, I haven't figured out how to start the site locally yet, so haven't checked this out.  Hopefully it looks good!

**Comment by NewMexicoKid** [comment]
Russ,
If you have a website, you can use jekyll to populate the static pages. E.g., I have a site at teiru.net, so my command line for building the test site is: 
`jekyll build --incremental -s . -d ~/teiru.net/InnerSourceCommons/`

The README.md has instructions for installing jekyll.

**Comment by rrrutledge** [comment]
Thanks, Tim.  I got the site running locally (served up with [http-server](https://www.npmjs.com/package/http-server).  Everything looks good!  Merge?

**Pull request merged**
